#Server IP - If not localhost you are going to need to allow remote connections in Redis Config
redis-server: 127.0.0.1
#Redis port - Default is 6379
redis-port: 6379
#Collect kill and death stats
kill-death-stats: true
#Collect join stats
join-stats: true
#Collect block break stats
block-breaks: true
#Collect blocks placed stats
blocks-placed: true
#Global play time
time-played: true